CREATE TABLE gamesTBL (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	kills INTEGER NOT NULL,
	deaths INTEGER NOT NULL,
	assists INTEGER NOT NULL );

CREATE TABLE playerTBL (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL );